In [6]:
import numpy as np

T, H = 5, 4
# hs = np.random.randn(T, H)
hs = np.arange(20).reshape(5,4)
print(hs)
a  = np.array([0.8, 0.1, 0.03, 0.05, 0.02])
print(a)
ar = a.reshape(T, 1)
print(ar)
ar = ar.repeat(H, axis=1)
print(ar)


t = hs * ar
print(t)

c = np.sum(t, axis=0)
print(c.shape)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[0.8  0.1  0.03 0.05 0.02]
[[0.8 ]
 [0.1 ]
 [0.03]
 [0.05]
 [0.02]]
[[0.8  0.8  0.8  0.8 ]
 [0.1  0.1  0.1  0.1 ]
 [0.03 0.03 0.03 0.03]
 [0.05 0.05 0.05 0.05]
 [0.02 0.02 0.02 0.02]]
[[0.   0.8  1.6  2.4 ]
 [0.4  0.5  0.6  0.7 ]
 [0.24 0.27 0.3  0.33]
 [0.6  0.65 0.7  0.75]
 [0.32 0.34 0.36 0.38]]
(4,)
[1.56 2.56 3.56 4.56]


In [11]:
import numpy as np

N, T, H = 1, 3, 4
# hs = np.random.randn(N, T, H)
# a  = np.random.randn(N, T)

hs = np.arange(12).reshape(N,T,H)
print(hs)

a  = np.array([[0.8,0.1,0.1]])
print(a)
ar = a.reshape(N, T, 1)
print(ar)
ar = ar.repeat(H, axis=2)
print(ar)

t = hs * ar
print(t)

c = np.sum(t, axis=1)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[0.8 0.1 0.1]]
[[[0.8]
  [0.1]
  [0.1]]]
[[[0.8 0.8 0.8 0.8]
  [0.1 0.1 0.1 0.1]
  [0.1 0.1 0.1 0.1]]]
[[[0.  0.8 1.6 2.4]
  [0.4 0.5 0.6 0.7]
  [0.8 0.9 1.  1.1]]]
[[1.2 2.2 3.2 4.2]]


In [17]:
import numpy as np

N, T, H = 2, 3, 4
# hs = np.random.randn(N, T, H)
# a  = np.random.randn(N, T)

hs = np.arange(24).reshape(N,T,H)
print(hs)

a  = np.array([[0.8,0.1,0.1] , 
               [0.7,0.2,0.1]])
print(a)
ar = a.reshape(N, T, 1)
print(ar)
ar = ar.repeat(H, axis=2)
print(ar)

t = hs * ar
print(t)

c = np.sum(t, axis=1)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[0.8 0.1 0.1]
 [0.7 0.2 0.1]]
[[[0.8]
  [0.1]
  [0.1]]

 [[0.7]
  [0.2]
  [0.1]]]
[[[0.8 0.8 0.8 0.8]
  [0.1 0.1 0.1 0.1]
  [0.1 0.1 0.1 0.1]]

 [[0.7 0.7 0.7 0.7]
  [0.2 0.2 0.2 0.2]
  [0.1 0.1 0.1 0.1]]]
[[[ 0.   0.8  1.6  2.4]
  [ 0.4  0.5  0.6  0.7]
  [ 0.8  0.9  1.   1.1]]

 [[ 8.4  9.1  9.8 10.5]
  [ 3.2  3.4  3.6  3.8]
  [ 2.   2.1  2.2  2.3]]]
[[ 1.2  2.2  3.2  4.2]
 [13.6 14.6 15.6 16.6]]


In [18]:
import sys
sys.path.append("..")
from common.layers import Softmax
import numpy as np

N, T, H = 10, 5, 4
hs = np.random.randn(N, T, H)
h  = np.random.randn(N, H)

hr = h.reshape(N, 1, H).repeat(T, axis=1)

t = hs * hr
print(t.shape)

s = np.sum(t, axis=2)
print(s.shape)

softmax = Softmax()
a = softmax.forward(s)
print(a.shape)
print(a)

(10, 5, 4)
(10, 5)
(10, 5)
[[2.44825013e-01 1.01112322e-02 7.56494109e-03 7.46376396e-02
  6.62861174e-01]
 [3.55937962e-01 2.03750119e-01 1.99416921e-02 9.06204507e-02
  3.29749775e-01]
 [4.30328343e-03 4.42405012e-01 6.01830972e-03 5.37734276e-01
  9.53911887e-03]
 [1.23351148e-01 3.48037295e-01 4.16076327e-01 2.67672456e-02
  8.57679850e-02]
 [9.53714399e-02 2.37298682e-04 1.02841847e-02 8.86490363e-01
  7.61671389e-03]
 [7.86374457e-03 6.70624538e-03 9.63987112e-01 1.03002360e-02
  1.11426622e-02]
 [1.11757821e-01 3.50027709e-02 8.42886035e-01 8.92437111e-03
  1.42900286e-03]
 [2.35466551e-02 8.38747253e-01 1.38550586e-03 3.45925021e-02
  1.01728084e-01]
 [7.80067051e-01 9.54611675e-02 8.26571127e-03 1.12917347e-01
  3.28872248e-03]
 [2.60467150e-02 9.12605090e-03 4.82275966e-02 4.62803822e-02
  8.70319255e-01]]


In [ ]:
# coding: utf-8
import sys
sys.path.append('..')
from common.np import *  # import numpy as np
from common.layers import Softmax


class WeightSum:
    def __init__(self):
        self.params, self.grads = [], []
        self.cache = None

    def forward(self, hs, a):
        N, T, H = hs.shape

        ar = a.reshape(N, T, 1).repeat(T, axis=1)
        t = hs * ar
        c = np.sum(t, axis=1)

        self.cache = (hs, ar)
        return c

    def backward(self, dc):
        hs, ar = self.cache
        N, T, H = hs.shape
        dt = dc.reshape(N, 1, H).repeat(T, axis=1)
        dar = dt * hs
        dhs = dt * ar
        da = np.sum(dar, axis=2)

        return dhs, da


class AttentionWeight:
    def __init__(self):
        self.params, self.grads = [], []
        self.softmax = Softmax()
        self.cache = None

    def forward(self, hs, h):
        N, T, H = hs.shape

        hr = h.reshape(N, 1, H).repeat(T, axis=1)
        t = hs * hr
        s = np.sum(t, axis=2)
        a = self.softmax.forward(s)

        self.cache = (hs, hr)
        return a

    def backward(self, da):
        hs, hr = self.cache
        N, T, H = hs.shape

        ds = self.softmax.backward(da)
        dt = ds.reshape(N, T, 1).repeat(H, axis=2)
        dhs = dt * hr
        dhr = dt * hs
        dh = np.sum(dhr, axis=1)

        return dhs, dh


class Attention:
    def __init__(self):
        self.params, self.grads = [], []
        self.attention_weight_layer = AttentionWeight()
        self.weight_sum_layer = WeightSum()
        self.attention_weight = None

    def forward(self, hs, h):
        a = self.attention_weight_layer.forward(hs, h)
        out = self.weight_sum_layer.forward(hs, a)
        self.attention_weight = a
        return out

    def backward(self, dout):
        dhs0, da = self.weight_sum_layer.backward(dout)
        dhs1, dh = self.attention_weight_layer.backward(da)
        dhs = dhs0 + dhs1
        return dhs, dh


class TimeAttention:
    def __init__(self):
        self.params, self.grads = [], []
        self.layers = None
        self.attention_weights = None

    def forward(self, hs_enc, hs_dec):
        N, T, H = hs_dec.shape
        out = np.empty_like(hs_dec)
        self.layers = []
        self.attention_weights = []

        for t in range(T):
            layer = Attention()
            out[:, t, :] = layer.forward(hs_enc, hs_dec[:,t,:])
            self.layers.append(layer)
            self.attention_weights.append(layer.attention_weight)

        return out

    def backward(self, dout):
        N, T, H = dout.shape
        dhs_enc = 0
        dhs_dec = np.empty_like(dout)

        for t in range(T):
            layer = self.layers[t]
            dhs, dh = layer.backward(dout[:, t, :])
            dhs_enc += dhs
            dhs_dec[:,t,:] = dh

        return dhs_enc, dhs_dec
