In [6]:
import numpy as np

T, H = 5, 4
# hs = np.random.randn(T, H)
hs = np.arange(20).reshape(5,4)
print(hs)
a  = np.array([0.8, 0.1, 0.03, 0.05, 0.02])
print(a)
ar = a.reshape(T, 1)
print(ar)
ar = ar.repeat(H, axis=1)
print(ar)


t = hs * ar
print(t)

c = np.sum(t, axis=0)
print(c.shape)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[0.8  0.1  0.03 0.05 0.02]
[[0.8 ]
 [0.1 ]
 [0.03]
 [0.05]
 [0.02]]
[[0.8  0.8  0.8  0.8 ]
 [0.1  0.1  0.1  0.1 ]
 [0.03 0.03 0.03 0.03]
 [0.05 0.05 0.05 0.05]
 [0.02 0.02 0.02 0.02]]
[[0.   0.8  1.6  2.4 ]
 [0.4  0.5  0.6  0.7 ]
 [0.24 0.27 0.3  0.33]
 [0.6  0.65 0.7  0.75]
 [0.32 0.34 0.36 0.38]]
(4,)
[1.56 2.56 3.56 4.56]


In [11]:
import numpy as np

N, T, H = 1, 3, 4
# hs = np.random.randn(N, T, H)
# a  = np.random.randn(N, T)

hs = np.arange(12).reshape(N,T,H)
print(hs)

a  = np.array([[0.8,0.1,0.1]])
print(a)
ar = a.reshape(N, T, 1)
print(ar)
ar = ar.repeat(H, axis=2)
print(ar)

t = hs * ar
print(t)

c = np.sum(t, axis=1)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[0.8 0.1 0.1]]
[[[0.8]
  [0.1]
  [0.1]]]
[[[0.8 0.8 0.8 0.8]
  [0.1 0.1 0.1 0.1]
  [0.1 0.1 0.1 0.1]]]
[[[0.  0.8 1.6 2.4]
  [0.4 0.5 0.6 0.7]
  [0.8 0.9 1.  1.1]]]
[[1.2 2.2 3.2 4.2]]


In [17]:
import numpy as np

N, T, H = 2, 3, 4
# hs = np.random.randn(N, T, H)
# a  = np.random.randn(N, T)

hs = np.arange(24).reshape(N,T,H)
print(hs)

a  = np.array([[0.8,0.1,0.1] , 
               [0.7,0.2,0.1]])
print(a)
ar = a.reshape(N, T, 1)
print(ar)
ar = ar.repeat(H, axis=2)
print(ar)

t = hs * ar
print(t)

c = np.sum(t, axis=1)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[0.8 0.1 0.1]
 [0.7 0.2 0.1]]
[[[0.8]
  [0.1]
  [0.1]]

 [[0.7]
  [0.2]
  [0.1]]]
[[[0.8 0.8 0.8 0.8]
  [0.1 0.1 0.1 0.1]
  [0.1 0.1 0.1 0.1]]

 [[0.7 0.7 0.7 0.7]
  [0.2 0.2 0.2 0.2]
  [0.1 0.1 0.1 0.1]]]
[[[ 0.   0.8  1.6  2.4]
  [ 0.4  0.5  0.6  0.7]
  [ 0.8  0.9  1.   1.1]]

 [[ 8.4  9.1  9.8 10.5]
  [ 3.2  3.4  3.6  3.8]
  [ 2.   2.1  2.2  2.3]]]
[[ 1.2  2.2  3.2  4.2]
 [13.6 14.6 15.6 16.6]]


In [1]:
import sys
sys.path.append("..")
from common.layers import Softmax
import numpy as np

N, T, H = 10, 5, 4
hs = np.random.randn(N, T, H)
h  = np.random.randn(N, H)

hr = h.reshape(N, 1, H).repeat(T, axis=1)

t = hs * hr
print(t.shape)

s = np.sum(t, axis=2)
print(s.shape)

softmax = Softmax()
a = softmax.forward(s)
print(a.shape)
print(a)

(10, 5, 4)
(10, 5)
(10, 5)
[[3.57414655e-01 2.40572408e-01 8.84110125e-02 1.32731455e-01
  1.80870470e-01]
 [8.91938616e-02 8.13169806e-02 3.57285385e-02 2.33682684e-01
  5.60077935e-01]
 [3.65113696e-04 6.00754297e-03 3.25329427e-02 4.11627772e-02
  9.19931623e-01]
 [1.54707470e-01 4.36919181e-02 2.02824833e-01 3.66443878e-01
  2.32331901e-01]
 [2.42475279e-02 9.53864593e-04 2.82493622e-03 1.57694160e-01
  8.14279511e-01]
 [2.65783252e-01 4.18035228e-01 2.19013289e-02 2.34949144e-01
  5.93310469e-02]
 [1.55566861e-01 4.96934981e-01 1.42970823e-01 7.05016192e-02
  1.34025716e-01]
 [2.23907602e-01 4.47334798e-01 1.83602044e-01 5.16914615e-02
  9.34640952e-02]
 [5.08546703e-02 1.16240280e-01 1.09783501e-01 2.76458577e-01
  4.46662972e-01]
 [5.61253699e-01 6.42263047e-03 4.23261789e-02 9.40222306e-03
  3.80595269e-01]]


In [4]:
a = np.array([1,2,-3,0,5])
# b = np.array([1,2,-3,0,5])
b = np.array([1,2,3,0,5])
c = np.dot(a,b)
print(c)

21


In [5]:
# coding: utf-8
import sys
sys.path.append('..')
from common.np import *  # import numpy as np
from common.layers import Softmax


class WeightSum:
    def __init__(self):
        self.params, self.grads = [], []
        self.cache = None

    def forward(self, hs, a):
        N, T, H = hs.shape

        ar = a.reshape(N, T, 1).repeat(T, axis=1)
        t = hs * ar
        c = np.sum(t, axis=1)

        self.cache = (hs, ar)
        return c

    def backward(self, dc):
        hs, ar = self.cache
        N, T, H = hs.shape
        dt = dc.reshape(N, 1, H).repeat(T, axis=1)
        dar = dt * hs
        dhs = dt * ar
        da = np.sum(dar, axis=2)

        return dhs, da


class AttentionWeight:
    def __init__(self):
        self.params, self.grads = [], []
        self.softmax = Softmax()
        self.cache = None

    def forward(self, hs, h):
        N, T, H = hs.shape

        hr = h.reshape(N, 1, H).repeat(T, axis=1)
        t = hs * hr
        s = np.sum(t, axis=2)
        a = self.softmax.forward(s)

        self.cache = (hs, hr)
        return a

    def backward(self, da):
        hs, hr = self.cache
        N, T, H = hs.shape

        ds = self.softmax.backward(da)
        dt = ds.reshape(N, T, 1).repeat(H, axis=2)
        dhs = dt * hr
        dhr = dt * hs
        dh = np.sum(dhr, axis=1)

        return dhs, dh


class Attention:
    def __init__(self):
        self.params, self.grads = [], []
        self.attention_weight_layer = AttentionWeight()
        self.weight_sum_layer = WeightSum()
        self.attention_weight = None

    def forward(self, hs, h):
        a = self.attention_weight_layer.forward(hs, h)
        out = self.weight_sum_layer.forward(hs, a)
        self.attention_weight = a
        return out

    def backward(self, dout):
        dhs0, da = self.weight_sum_layer.backward(dout)
        dhs1, dh = self.attention_weight_layer.backward(da)
        dhs = dhs0 + dhs1
        return dhs, dh


class TimeAttention:
    def __init__(self):
        self.params, self.grads = [], []
        self.layers = None
        self.attention_weights = None

    def forward(self, hs_enc, hs_dec):
        N, T, H = hs_dec.shape
        out = np.empty_like(hs_dec)
        self.layers = []
        self.attention_weights = []

        for t in range(T):
            layer = Attention()
            out[:, t, :] = layer.forward(hs_enc, hs_dec[:,t,:])
            self.layers.append(layer)
            self.attention_weights.append(layer.attention_weight)

        return out

    def backward(self, dout):
        N, T, H = dout.shape
        dhs_enc = 0
        dhs_dec = np.empty_like(dout)

        for t in range(T):
            layer = self.layers[t]
            dhs, dh = layer.backward(dout[:, t, :])
            dhs_enc += dhs
            dhs_dec[:,t,:] = dh

        return dhs_enc, dhs_dec


In [8]:
aw = AttentionWeight()
h = np.array([[1,0,-1,-2]])
hs = np.array(
[[[1,0,-1,-1],
  [0,1,2,1],
  [0,0,1,1],
  [1,1,0,0],
  [0,1,0,1]]] 
)
print(hs)
a = aw.forward(hs, h)
print(a)

[[[ 1  0 -1 -1]
  [ 0  1  2  1]
  [ 0  0  1  1]
  [ 1  1  0  0]
  [ 0  1  0  1]]]
[[9.49205034e-01 3.18422815e-04 8.65562952e-04 4.72581359e-02
  2.35284404e-03]]
