### seq2seq

In [19]:
import sys
sys.path.append('..')

file_path = "../dataset/addition.txt"

questions, answers = [], []
for line in open(file_path, 'r'):
    idx = line.find('_')
    questions.append(line[:idx])
    answers.append(line[idx:-1])
print("[%s]"%questions[0])
print("[%s]"%answers[0])

[16+75  ]
[_91  ]


In [27]:
id_to_char = {}
char_to_id = {}
def _update_vocab(txt):
    chars = list(txt)
#     print(chars)
    for i, char in enumerate(chars):
        if char not in char_to_id:
            tmp_id = len(char_to_id)
            char_to_id[char] = tmp_id
            id_to_char[tmp_id] = char

In [28]:
for i in range(len(questions)):
    q, a = questions[i], answers[i]
    _update_vocab(q)
    _update_vocab(a)
    
print(char_to_id)
print(id_to_char)

{'1': 0, '6': 1, '+': 2, '7': 3, '5': 4, ' ': 5, '_': 6, '9': 7, '2': 8, '0': 9, '3': 10, '8': 11, '4': 12}
{0: '1', 1: '6', 2: '+', 3: '7', 4: '5', 5: ' ', 6: '_', 7: '9', 8: '2', 9: '0', 10: '3', 11: '8', 12: '4'}


In [31]:
x = np.zeros((len(questions), len(questions[0])), dtype=np.int)
t = np.zeros((len(questions), len(answers[0])), dtype=np.int)
print(x.shape)
print(t.shape)

(50000, 7)
(50000, 5)


In [33]:
for i, sentence in enumerate(questions):
    x[i] = [char_to_id[c] for c in list(sentence)]
for i, sentence in enumerate(answers):
    t[i] = [char_to_id[c] for c in list(sentence)]
    
print(x[0])
print(t[0])

[0 1 2 3 4 5 5]
[6 7 0 5 5]


In [41]:
# 뒤섞기
seed=1984
indices = np.arange(len(x))
if seed is not None:
    np.random.seed(seed)
np.random.shuffle(indices)
x = x[indices]
t = t[indices]

print(x[0])
print(t[0])

[1 4 4 2 7 8 1]
[ 6  0  4 11  0]


In [43]:
# 검증 데이터셋으로 10% 할당
split_at = len(x) - len(x) // 10
(x_train, x_test) = x[:split_at], x[split_at:]
(t_train, t_test) = t[:split_at], t[split_at:]
print(x_train.shape)
print(x_test.shape)
print(t_train.shape)
print(t_test.shape)

(45000, 7)
(5000, 7)
(45000, 5)
(5000, 5)


In [45]:
# coding: utf-8
import sys
sys.path.append('..')
from dataset import sequence

(x_train, t_train), (x_test, t_test) = \
    sequence.load_data('addition.txt', seed=1984)
char_to_id, id_to_char = sequence.get_vocab()

print(char_to_id)
print(x_train.shape, t_train.shape)
# print(x_test.shape, t_test.shape)
# (45000, 7) (5000, 7)
# (5000, 7) (5000, 5)

# print(x_train[0])
# print(t_train[0])
# [ 3  0  2  0  0 11  5]
# [ 6  0 11  7  5]

# print(''.join([id_to_char[c] for c in x_train[0]]))
# print(''.join([id_to_char[c] for c in t_train[0]]))
# 71+118
# _189

{'1': 0, '6': 1, '+': 2, '7': 3, '5': 4, ' ': 5, '_': 6, '9': 7, '2': 8, '0': 9, '3': 10, '8': 11, '4': 12}
(45000, 7) (45000, 5)
